<a href="https://colab.research.google.com/github/Avit-hodibu/dataCollection/blob/main/Data_gathering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Work with CSV file
comma seperated value = seperated by comma
tsb (tab seperated value)

In [1]:
# import pandas
import pandas as pd

In [3]:
#open local csv file
df= pd.read_csv('/content/aug_train.csv')

In [4]:
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [5]:
#open a csv file from URL
# use this code snippet directly if you are calling from website
import requests
from io import StringIO

# url of site
url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
# by using requests.get() load the content of that website and store in req
req = requests.get(url, headers=headers)
# now only select the text from req
data = StringIO(req.text)
#read the text data
df_url=pd.read_csv(data)
df_url.head()

    Country  Region
0   Algeria  AFRICA
1    Angola  AFRICA
2     Benin  AFRICA
3  Botswana  AFRICA
4   Burkina  AFRICA

In [6]:
# when the seperator is not comma, we need to use sep ='' in parameter
# and place the symbol that seperate text of the data
# default is sep= ',' . so, we donot need to use for csv file
# but for tsv we need to use '\t that is tab
# tsv = tab seperate value
# since col does not have name so we use names= [] to set col name
df_tsv=pd.read_csv('/content/movie_titles_metadata.tsv', sep='\t', names=['sno','name','release_year','rating','votes','genres'])
df_tsv.head()

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']

In [7]:
# when col name is treated as row
# header of each col is show like data
# use header= parameter and set the row which need to be header
df_row=pd.read_csv('/content/test.csv', header=1) # count start from 1 not 0
df_row.head()

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [8]:
# changing col to index_col
# this is use by using parameter index_col =''
# put the col which you want to set as index inside comma
df_index=pd.read_csv('/content/aug_train.csv', index_col='enrollee_id')
df_index.head()

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [9]:
 # load only col which is need for you when loading or reading data
 # for that we need to use usecols=[] parameter and place the col name inside that you want to call
df_col = pd.read_csv('/content/aug_train.csv', usecols=['enrollee_id','gender','education_level'])
df_col.head()

   enrollee_id gender education_level
0         8949   Male        Graduate
1        29725   Male        Graduate
2        11561    NaN        Graduate
3        33241    NaN        Graduate
4          666   Male         Masters

In [10]:
# when need only one col
# change the pandas series use parameter squeeze=True
# but when we used to call it was changing to pandas dataframe
df_col_one=pd.read_csv('/content/aug_train.csv', usecols=['enrollee_id']).squeeze()
df_col_one.head()

0     8949
1    29725
2    11561
3    33241
4      666
Name: enrollee_id, dtype: int64

In [11]:
# skiprows Parameter
# no load of data from that rows
# place the index number skiprows=[] parameter
df_skip=pd.read_csv('/content/aug_train.csv', skiprows=[0,1])
df_skip.head()

,29725,city_40,0.7759999999999999,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
0,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
1,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
4,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0

In [12]:
# load only denote number of rows
# use parameter nrows=
df_nrows=pd.read_csv('/content/aug_train.csv', nrows=4)
df_nrows.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0

In [13]:
# mostly encoded in utf-8 in text and numberical
# emoji and different languages encoded in different
# error is show when it is not utf-8 ---> UnicodeDecodeError
# use parameter encoding='' and place the encode file text
# or change the encoding using text editor

# this is encode in latin-1
df_encode =pd.read_csv('/content/zomato.csv', encoding='latin-1')
df_encode.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [20]:
#skip bad lines
#this will automaticlly skip the line or row which give error
#use in parser error
# on_bad_lines='error' set this
df_bad =pd.read_csv('/content/zomato.csv', encoding='latin-1', on_bad_lines='error')
df_bad.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [21]:
#dtypes parameter
# change the data type of col
df_dt = pd.read_csv('/content/aug_train.csv', dtype={'target':int})
df_dt.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [22]:
# handling date
df_date= pd.read_csv('/content/IPL Matches 2008-2020.csv', parse_dates=['date'])
# now it will treated as date not object
df_date.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [23]:
df_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

In [24]:
# transformation or converter
# transform the data usinf converters
def rename(name):
  if name == "Royal Challengers Bangalore":
    return "RCB"
  else:
    return name

pd_convert= pd.read_csv('/content/IPL Matches 2008-2020.csv', converters={'team1': rename})
pd_convert.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [25]:
# what type of value is consider as NaN vlaue
# we denote using parameter na_values=[]
# male is change to NaN
df_na = pd.read_csv('/content/aug_train.csv', na_values=['Male'])
df_na.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [26]:
# load a huge dataset in chunks
# denote the chunk size we want to create
dfs = pd.read_csv('/content/aug_train.csv', chunksize=1000)
#loaded in small chunks one by one
for chunks in dfs:
  print(chunks.shape)

(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(158, 14)

#Working with JSON/SQL
API= JSON
DB= SQL
json is understand by all programming language

## JSON

In [27]:
import pandas as pd
# to change to df
df_json=pd.read_json('/content/train.json')

In [28]:
df_json.head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [29]:
#load from url
df_json_url=pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')
df_json_url.head()

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-08-19,1724025601,0.0438
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-08-19,1724025601,0.8460
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-08-19,1724025601,1.0800
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-08-19,1724025601,4.6200
ANG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-08-19,1724025601,0.0213

##SQL

1. run the database file which is in sql formate in local db by importing db in sql db
2. install connector. in this case we are using mysql so, !pip install mysql.connector
3. from a connection to db
4. read that and put in pandas dataframe

In [31]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 44.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py) ... done
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp310-cp310-linux_x86_64.whl size=247948 sha256=11b1e9fb5ce297b799a0d360c3dd465f0739b23c89ae5feec482224b100726ba
  Stored in directory: /root/.cache/pip/wheels/76/48/9b/da67ff1a18fe8e9d428f9b1a177716d4a7d363d2bbe83bf6cf
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [32]:
import mysql.connector

In [ ]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='samplevideo_db')

In [ ]:
# use sql query to call the data
df_sql=pd.read_sql_query("SELECT * FROM user_details",conn)

#Fetch Data from API

communicator medium between two software = API = Data pipelines

1. get api from site
2. put your api key
3. if you put in browser with key you will find data in json formate
4. if you want to look data if you do not understand copy data and paste in https://jsonviewer.stack.hu/

In [34]:
import pandas as pd
# for http request
import requests

In [35]:
# requests sending request to http which wil give us a data of that url
response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1%27')
# now the send data by http after request is place in json formate
response.json()

# since i need only the 'results' and this is in dict
response_json= response.json()['results']
# changing into pandas dataframe
df_api=pd.DataFrame(response_json)

In [36]:
df_api.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/avedvodAZUcwqevBfm8p4G2NziQ.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,251.609,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.706,26651
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",260.391,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.690,20215
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,97.287,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.575,12199
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,188.831,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.565,15603
4,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,73.518,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.543,8445

In [37]:
#since site has many pages so we need to do in loop to extract all data

df_api_all=pd.DataFrame()
page_number=5
for i in range(1,page_number):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df_api_all = df_api_all._append(temp_df,ignore_index=True)

In [38]:
df_api_all.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,179.721,8.706,26650
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,282.604,8.690,20214
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,86.910,8.575,12198
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,134.879,8.565,15603
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,66.779,8.543,8444

In [39]:
# to export
df_api_all.to_csv('movie.csv')

#### go in rapidaip.com and get api -> make dataset

# Web scraping

if not given api of app then web scraping is only the option

In [1]:
import pandas as pd
import requests
# web scraping lib
from bs4 import BeautifulSoup

In [2]:
response=requests.get('https://www.ambitionbox.com/list-of-companies?page=1')

In [3]:
print(response)
# reponse [403] means sever has deny request.
response.content

<Response [403]>

b'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;www&#46;ambitionbox&#46;com&#47;list&#45;of&#45;companies&#63;" on this server.<P>\nReference&#32;&#35;18&#46;de213517&#46;1724033980&#46;b8765f4\n<P>https&#58;&#47;&#47;errors&#46;edgesuite&#46;net&#47;18&#46;de213517&#46;1724033980&#46;b8765f4</P>\n</BODY>\n</HTML>\n'

This site has use Robox.txt concept. In which file are put which you dont want to see by crawler. so, that web scraper or google search won't able to crawl.

For that there is one solution that we need to show our request is send from browser.

We "header" so that is send by human from browser.

### this is only work for page 1
if you want to run page more page use for loop:
```
# j give the page number
final = pd.DataFrame()
for j in range(1,1001):
  webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page={}'.format(j)).text
  soup=BeautifulSoup(webpage,'lxml')
  #other same
# at last
final = final._append(df, ignore_index = True)
```

In [ ]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers=headers)
# this will give whole html code of that page

In [ ]:
response_work.content

In [ ]:
#beautifulSoup is lib use for web scraping
soup=BeautifulSoup(webpage,'lxml')
#This help in traverse in the html code

In [ ]:
# arrange the content in html structure
print(soup.prettify())

In [ ]:
# this will give all the p tag which has class name rating from the given page
soup.find_all('p', class_='rating')

# like this
soup.find_all('a', class_='review-count').text

In [ ]:
company= soup.find_all('div', class_='company-content-wrapper')
name =[]
rating=[]
reviews=[]
ctype=[]
hq=[]
how_old=[]
no_of_employee=[]
for i in company:
  #find means single
  #.text give value in text
  #.strip will strip space
  name.append(i.find('h2').text.strip())
  rating.append(i.find('p', class_='rating').text.strip())
  reviews.append(i.find('a', class_='review-count').text.strip())
  # [0] because when p class is call with find_all it will provide 4 entity
  # because they have use same class style
  #so, when [0] it will only call 1st index value
  ctype.append(i.find_all('p', class_='infoEntity')[0].text.strip())
  # similarly [1] means 2nd index value
  hq.append(i.find_all('p', class_='infoEntity')[1].text.strip())
  how_old.append(i.find_all('p', class_='infoEntity')[2].text.strip())
  no_of_employee.append(i.find_all('p', class_='infoEntity')[3].text.strip())

In [ ]:
# create dataframe
dict_data = {'name':name, 'rating':rating, 'reviews':reviews, 'ctype':ctype, 'hq':hq, 'how_old':how_old, 'no_of_employee':no_of_employee}
df=pd.DataFrame(dict_data)

In [ ]:
df.head()